app:
  port: 3000
  timeout: 30000
  prefix: /react-admin-api
  assetsPrefix: /react-admin-assets
  loginCaptcha: true
mysql:
  host: localhost
  port: 3306
  database: react-admin
  username: root
  password: 3iceh067x8(7W+
  timezone: +08:00
  synchronize: false
  logging: false
redis:
  host: localhost
  port: 6379
  password: Hi0m4!KxhmkHX
  db: 0
logger:
  level: debug
  dirname: react-admin-backend-logs/daily-log
  filename: app-%DATE%.log
  datePattern: YYYY-MM-DD
  maxSize: 1M,
  host: localhost
  port: 3001
  path: /react-admin-api-logs
jwt:
  secret: WRm0C3vkyT1KdYJdpF2D3lRcIiNtD6C721BSHe3yyxTJVH2s6jBg6OTiO23G
  expiresIn: 2h
  refreshTokenExpiresIn: 7d
captcha:
  width: 100
  height: 50
  length: 4
  ttl: 60
  enable: true